export const ENDPOINTS = {
  meta: 'meta',
  emojis: 'emojis',
  i: 'i',
  notesTimeline: 'notes/timeline',
  notesLocalTimeline: 'notes/local-timeline',
  notesGlobalTimeline: 'notes/global-timeline',
  notesUserListTimeline: 'notes/user-list-timeline',
  notesShow: 'notes/show',
  notesSearchByTag: 'notes/search-by-tag',
  notesReplies: 'notes/replies',
  notesCreate: 'notes/create',
  notesReactionsCreate: 'notes/reactions/create',
  notesReactionsDelete: 'notes/reactions/delete',
  favoritesCreate: 'notes/favorites/create',
  favoritesDelete: 'notes/favorites/delete',
  favoritesList: 'i/favorites',
  clipsList: 'clips/list',
  clipsAddNote: 'clips/add-note',
  clipsRemoveNote: 'clips/remove-note',
  clipsNotes: 'clips/notes',
  usersShow: 'users/show',
  usersNotes: 'users/notes',
  usersListsList: 'users/lists/list',
  usersListsPush: 'users/lists/push',
  followingCreate: 'following/create',
  followingDelete: 'following/delete',
  driveFilesCreate: 'drive/files/create',
  driveFilesUpdate: 'drive/files/update',
  miauthCheck: (sessionId: string) => `miauth/${sessionId}/check`
} as const;
